-- ============================================================
-- SQL File Detection Tool demo: encoding vs. collation
-- ------------------------------------------------------------
-- Generated by data sample/generate_samples.py - do not edit by hand.
--
-- File ENCODING (UTF-8, UTF-16LE, CP932, ...) decides which bytes
-- represent a character on disk. SQL COLLATION decides how the
-- server compares, sorts and groups those characters once they
-- are inside an NVARCHAR column or expression. A CSV or JSON file
-- never carries a collation.
--
-- The script only creates a #temp table, so it is safe to run in
-- any database.
-- ============================================================
SET NOCOUNT ON;
GO

-- ------------------------------------------------------------
-- 0. Which of the collations used below does this instance have?
--    Check this first: collation availability depends on the
--    SQL Server / Azure SQL version.
-- ------------------------------------------------------------
SELECT [name], [description]
FROM sys.fn_helpcollations()
WHERE [name] IN (N'Japanese_XJIS_140_CI_AS_KS_WS',
                 N'Japanese_XJIS_140_CI_AI',
                 N'Japanese_Bushu_Kakusu_140_CI_AS',
                 N'Latin1_General_100_CI_AI',
                 N'Latin1_General_100_CI_AS',
                 N'Latin1_General_100_CS_AS',
                 N'Latin1_General_100_BIN2_UTF8',
                 N'Turkish_100_CI_AS')
ORDER BY [name];
GO

-- ------------------------------------------------------------
-- 1. Load the demo values. NVARCHAR + N-prefixed literals keep
--    every code point, including supplementary-plane emoji.
-- ------------------------------------------------------------
IF OBJECT_ID(N'tempdb..#collation_demo') IS NOT NULL
    DROP TABLE #collation_demo;
GO

CREATE TABLE #collation_demo (
    [pair_id]       INT            NOT NULL PRIMARY KEY,
    [category]      NVARCHAR(64)   NOT NULL,
    [left_value]    NVARCHAR(200)  NULL,
    [right_value]   NVARCHAR(200)  NULL,
    [differs_under] NVARCHAR(200)  NULL
);
GO

INSERT INTO #collation_demo
    ([pair_id], [category], [left_value], [right_value], [differs_under])
VALUES
    (1, N'kana_type', N'ひらがな', N'ヒラガナ', N'kana sensitivity (_KS)'),
    (2, N'kana_width', N'カタカナ', N'ｶﾀｶﾅ', N'width sensitivity (_WS)'),
    (3, N'latin_width', N'ABC123', N'ＡＢＣ１２３', N'width sensitivity (_WS)'),
    (4, N'case', N'straße', N'STRASSE', N'case sensitivity (_CS)'),
    (5, N'sharp_s', N'straße', N'strasse', N'German sharp s expansion'),
    (6, N'accent', N'resume', N'résumé', N'accent sensitivity (_AS)'),
    (7, N'unicode_form', N'café', N'café', N'binary collations only (_BIN2)'),
    (8, N'turkish_i', N'ISTANBUL', N'istanbul', N'Turkish_100 dotless i'),
    (9, N'turkish_dotted', N'İstanbul', N'Istanbul', N'Turkish_100 dotted I'),
    (10, N'trailing_space', N'value', N'value   ', N'trailing spaces ignored by = but not by DATALENGTH'),
    (11, N'lookalike', N'A', N'Α', N'Latin A vs Greek Alpha'),
    (12, N'lookalike_cyrillic', N'A', N'А', N'Latin A vs Cyrillic A'),
    (13, N'kana_prolonged', N'コーヒー', N'コ－ヒ－', N'prolonged sound mark vs full-width hyphen'),
    (14, N'identical', N'😀', N'😀', N'identical supplementary-plane characters');
GO

-- ------------------------------------------------------------
-- 2. Japanese collations: kana type (_KS) and width (_WS).
--    Japanese_XJIS_140_* are the Unicode 14 Japanese collations.
--      _KS = kana sensitive   (hiragana <> katakana)
--      _WS = width sensitive  (full-width <> half-width)
--    Dropping _KS / _WS makes those pairs compare EQUAL.
-- ------------------------------------------------------------
SELECT
    [pair_id],
    [category],
    [left_value],
    [right_value],
    CASE WHEN [left_value] COLLATE Japanese_XJIS_140_CI_AS_KS_WS
              = [right_value] COLLATE Japanese_XJIS_140_CI_AS_KS_WS
         THEN N'equal' ELSE N'different' END AS [kana_width_sensitive],
    CASE WHEN [left_value] COLLATE Japanese_XJIS_140_CI_AI
              = [right_value] COLLATE Japanese_XJIS_140_CI_AI
         THEN N'equal' ELSE N'different' END AS [kana_width_insensitive]
FROM #collation_demo
WHERE [category] IN (N'kana_type', N'kana_width', N'kana_prolonged', N'latin_width')
ORDER BY [pair_id];
GO

-- ------------------------------------------------------------
-- 3. Case, accent and Unicode normalisation.
--    Only a binary (_BIN2) collation separates the composed and
--    decomposed forms of the same visible character.
-- ------------------------------------------------------------
SELECT
    [pair_id],
    [category],
    CASE WHEN [left_value] COLLATE Latin1_General_100_CI_AI
              = [right_value] COLLATE Latin1_General_100_CI_AI
         THEN N'equal' ELSE N'different' END AS [ci_ai],
    CASE WHEN [left_value] COLLATE Latin1_General_100_CS_AS
              = [right_value] COLLATE Latin1_General_100_CS_AS
         THEN N'equal' ELSE N'different' END AS [cs_as],
    CASE WHEN [left_value] COLLATE Latin1_General_100_BIN2_UTF8
              = [right_value] COLLATE Latin1_General_100_BIN2_UTF8
         THEN N'equal' ELSE N'different' END AS [binary_utf8],
    DATALENGTH([left_value])  AS [left_bytes],
    DATALENGTH([right_value]) AS [right_bytes]
FROM #collation_demo
WHERE [category] IN (N'case', N'sharp_s', N'accent', N'unicode_form', N'trailing_space', N'lookalike', N'lookalike_cyrillic')
ORDER BY [pair_id];
GO

-- ------------------------------------------------------------
-- 4. Turkish dotted / dotless I.
--    Turkish_100_CI_AS treats i / I and dotless i / dotted I
--    differently from Latin1_General_100_CI_AS.
-- ------------------------------------------------------------
SELECT
    [pair_id],
    [left_value],
    [right_value],
    CASE WHEN [left_value] COLLATE Turkish_100_CI_AS
              = [right_value] COLLATE Turkish_100_CI_AS
         THEN N'equal' ELSE N'different' END AS [turkish_ci_as],
    CASE WHEN [left_value] COLLATE Latin1_General_100_CI_AS
              = [right_value] COLLATE Latin1_General_100_CI_AS
         THEN N'equal' ELSE N'different' END AS [latin_ci_as]
FROM #collation_demo
WHERE [category] LIKE N'turkish%'
ORDER BY [pair_id];
GO

-- ------------------------------------------------------------
-- 5. Sort order depends on the collation.
--    Japanese_Bushu_Kakusu_140_CI_AS orders kanji by radical and
--    stroke count; a _BIN2 collation orders by code point.
-- ------------------------------------------------------------
SELECT [pair_id], [left_value]
FROM #collation_demo
ORDER BY [left_value] COLLATE Japanese_Bushu_Kakusu_140_CI_AS, [pair_id];
GO

SELECT [pair_id], [left_value]
FROM #collation_demo
ORDER BY [left_value] COLLATE Latin1_General_100_BIN2_UTF8, [pair_id];
GO

-- ------------------------------------------------------------
-- 6. Grouping collapses values the collation calls equal.
-- ------------------------------------------------------------
SELECT
    [left_value] COLLATE Japanese_XJIS_140_CI_AI AS [grouped_value],
    COUNT(*) AS [rows]
FROM #collation_demo
GROUP BY [left_value] COLLATE Japanese_XJIS_140_CI_AI
ORDER BY [grouped_value];
GO

-- ------------------------------------------------------------
-- 7. Clean up.
-- ------------------------------------------------------------
IF OBJECT_ID(N'tempdb..#collation_demo') IS NOT NULL
    DROP TABLE #collation_demo;
GO
