#!/usr/bin/env node
/**
 * Generate `THIRD_PARTY_NOTICES.md` from the packages actually bundled.
 *
 * The notice file has to match the shipped artifact, not the dependency tree:
 * `node_modules` never ships, tree shaking removes whole packages, and a
 * dev-only dependency creates no obligation at all. So the list is derived from
 * an esbuild metafile for the real production bundle — every `node_modules/...`
 * input that survived into `dist/extension.js`, and nothing else.
 *
 * Run with `--check` in CI to fail when the committed file is out of date.
 */

'use strict';

const fs = require('fs');
const path = require('path');
const esbuild = require('esbuild');
const { options: buildOptions } = require('./build');

const repoRoot = path.join(__dirname, '..');
const noticesPath = path.join(repoRoot, 'THIRD_PARTY_NOTICES.md');
const LICENSE_FILE_NAMES = [
    'LICENSE', 'LICENSE.md', 'LICENSE.txt', 'license', 'license.md', 'license.txt',
    'LICENCE', 'LICENCE.md', 'LICENCE.txt', 'COPYING', 'COPYING.md',
];

/**
 * Package names, and their on-disk locations, for every third-party input in
 * the bundle.
 *
 * The real build options are reused rather than restated. Restating them looks
 * harmless but silently drops `alias`, `treeShaking` and `define`, which change
 * the resolution graph — so the notices would describe a bundle nobody ships.
 */
async function bundledPackages() {
    const result = await esbuild.build({
        ...buildOptions,
        outfile: undefined,
        write: false,
        metafile: true,
        logLevel: 'silent',
    });
    // Keyed by package name, valued by the directory the bundler actually read
    // from, so a hoisting conflict reports the version that shipped rather than
    // whichever copy happens to sit at the repo root.
    const found = new Map();
    for (const input of Object.keys(result.metafile.inputs)) {
        const normalized = input.replace(/\\/g, '/');
        const match = /(?:^|\/)node_modules\/((?:@[^/]+\/)?[^/]+)\//.exec(normalized);
        if (!match || found.has(match[1])) {
            continue;
        }
        const directory = normalized.slice(0, match.index + match[0].length - 1);
        found.set(match[1], path.resolve(repoRoot, directory));
    }
    return [...found.entries()].sort((a, b) => a[0].localeCompare(b[0]));
}

function readPackage(name, dir) {
    const manifest = JSON.parse(fs.readFileSync(path.join(dir, 'package.json'), 'utf8'));
    let licenseText = null;
    for (const candidate of LICENSE_FILE_NAMES) {
        const file = path.join(dir, candidate);
        if (fs.existsSync(file) && fs.statSync(file).isFile()) {
            licenseText = fs.readFileSync(file, 'utf8').replace(/\r\n/g, '\n').trim();
            break;
        }
    }
    const license =
        typeof manifest.license === 'string'
            ? manifest.license
            : manifest.license?.type ?? (manifest.licenses ?? []).map((l) => l.type).join(' OR ');
    return {
        name,
        version: manifest.version,
        license: license || 'UNKNOWN',
        homepage: manifest.homepage ?? manifest.repository?.url ?? null,
        licenseText,
    };
}

function render(packages) {
    const lines = [
        '# Third party notices',
        '',
        'The SQL File Detection Tool VS Code extension ships a single bundled file,',
        '`dist/extension.js`. The packages below are compiled into that bundle and their',
        'license terms therefore apply to the distributed extension. `node_modules` is not',
        'part of the VSIX, and build-only tooling (TypeScript, esbuild, ESLint, vsce) is',
        'not listed because none of it is redistributed.',
        '',
        'This file is generated by `npm run notices` from the production bundle, so it',
        'always matches what is actually shipped.',
        '',
        '## Summary',
        '',
        '| Package | Version | License |',
        '| --- | --- | --- |',
    ];
    for (const pkg of packages) {
        lines.push(`| \`${pkg.name}\` | ${pkg.version} | ${pkg.license} |`);
    }
    lines.push('', '## Full license texts', '');
    for (const pkg of packages) {
        lines.push(`### ${pkg.name}@${pkg.version}`, '');
        if (pkg.homepage) {
            lines.push(`${String(pkg.homepage).replace(/^git\+/, '')}`, '');
        }
        lines.push('```text');
        lines.push(pkg.licenseText ?? `${pkg.license} (no license file published with the package)`);
        lines.push('```', '');
    }
    return `${lines.join('\n').replace(/\n+$/, '')}\n`;
}

async function main() {
    const found = await bundledPackages();
    const packages = found.map(([name, dir]) => readPackage(name, dir));
    const unknown = packages.filter((p) => p.license === 'UNKNOWN');
    if (unknown.length > 0) {
        throw new Error(`no license metadata for: ${unknown.map((p) => p.name).join(', ')}`);
    }
    const content = render(packages);

    if (process.argv.includes('--check')) {
        const current = fs.existsSync(noticesPath) ? fs.readFileSync(noticesPath, 'utf8') : '';
        if (current.replace(/\r\n/g, '\n') !== content) {
            throw new Error('THIRD_PARTY_NOTICES.md is out of date; run "npm run notices"');
        }
        // eslint-disable-next-line no-console
        console.log(`THIRD_PARTY_NOTICES.md is current (${packages.length} bundled packages)`);
        return;
    }

    fs.writeFileSync(noticesPath, content, 'utf8');
    // eslint-disable-next-line no-console
    console.log(`wrote THIRD_PARTY_NOTICES.md for ${packages.length} bundled packages`);
}

main().catch((error) => {
    console.error(error.message ?? error);
    process.exit(1);
});
